### ISSUE TITLE
Question about one equation

### ISSUE THREAD

**Issue by matthew-cruz** [stevenshave/PyBindingCurve#3]
Hello, in `systems/analytical_equations.py`, the function `system01_analytical_one_to_one__pl` has a `2.0` in the denominator. I am wondering if you have a reference for me with this form of the equation since the form I have seen more often has a `2.0*p` in the denominator. Is this taken care of elsewhere that I am just confused about?

**Comment by stevenshave** [comment]
You can follow the derivation of P&L complex concentration from the SI material in the accompanying publication (relevant section pasted below).  system01_analytical_one_to_one__pl returns the concentration of protein:ligand complex formed.  If you see a similar equation with 2.0*p in the denominator, then this is giving you fraction protein in complex (dividing the P:L complex concentration by the total amount protein). system01_analytical_one_to_one__pl reads out PL concentration as denoted by the __pl at the end.  pybindingcurve has options to change readouts with transformations such as dividing by total P or L to turn it into fraction protein or ligand bound (see pbc.Readout).  I hope this helps.

![image](https://user-images.githubusercontent.com/1618729/151694696-1723b838-ed1d-431f-a877-c25816557950.png)

**Comment by matthew-cruz** [comment]
Hi, thanks for the reply, this makes sense.
